### ISSUE TITLE
Problem with hypertext link in descriptions : links "project relative path" are not working

### ISSUE THREAD

**Issue by jeana-a** [eclipse-capella/capella#2585]
When inserting an hyperlink of type “project relative path”, nothing happen when we double click on the link (link to the word document on the picture)

Selecting all other options (URL, absolute path, elements of the model), the double click is working fine and we manage to open the target but with the “project relative path” option it is not the case.

![image](https://user-images.githubusercontent.com/124919625/218123083-cfe87f5a-6d0a-4f46-ae9c-ceff5c17e9f4.png)

**Comment by SteveMonnier** [comment]
[Capella2585Hypertext.zip](https://github.com/eclipse/capella/files/13358528/Capella2585Hypertext.zip)
With the Pull request, the scenario to validate this issue is:
* Import the project from the attached archive
* Select the "Root Operational Activity" model element
* Go to the "Description" tab
* Double-click the hypertext link
* Validation -> It should open the PDF file

**Comment by lfasani** [comment]
The PR https://github.com/eclipse/kitalpha/pull/775

**Comment by SteveMonnier** [comment]
Hi @jeana-a,
The PR has been merged in kitalpha and this issue can be closed.

**Comment by lredor** [comment]
As said by Steve the corresponding Kitalpha issue has been resolved.
