### ISSUE TITLE
Using Activity Explorer to transition Logical Capabilities to Physical Capabilities does not detect any capability

### ISSUE THREAD

**Issue by ldelaigue** [eclipse-capella/capella#2642]
Steps to reproduce:
- Use a Capella model with some Capability Realizations in the Logical Layer's 'Capabilities' package
- Use the Activity Explorer, in Physical Architecture tab, choose Enrich Physical Scenarios > Perform an automated transition of Logical Architecture Capabilities

This causes an empty diff/merge dialog to pop-up, where no Capability is present and thus nothing can be transitioned.

Notes:
- Doing the same from System Architecture to Logical Architecture works as expected
- Using the right-click menu 'Transition > Functional Transition' on the Logical Architecture's Capabilities packages works as expected

**Comment by etraisnel2** [comment]
After investigating

the "Perform an automated transition of Logical Architecture Capabilities" action is wired on a transition from System Analysis

https://github.com/eclipse/capella/blob/753d3d41f82c1b65697461337469773018394594/core/plugins/org.polarsys.capella.core.explorer.activity.ui/src/org/polarsys/capella/core/explorer/activity/ui/hyperlinkadapter/la/PerformAutomatedCapabilitiesTransitionAdapter.java#L44

Whereas the "Transition > Capabilities" is wired on the selection's block architecture (logical system in our case)

Needs more investigation to check if that's an expected behavior, or if we are missing a specific handler to transition from logical to physical
