### ISSUE TITLE
Switch to Eclipse 2023-03

### ISSUE THREAD

**Issue by etraisnel2** [eclipse-capella/capella#2659]
Prepare next version of Capella 

(OK) Switch to Java 17
- Update jdt compiler , classpaths, BREE
- Update JenkinsFile and poms

(OK) Integration :
- Sirius 7.2.0
- Eclipse-2023-03
- Orbit R20230302014618
- Mylyn 3.26
- Kitalpha 7.0.0
- DiffMerge 0.15.0
- Amalgam 1.14
- Nattable 2.1.0
- Nebula 3.0.0

(NOK) Continuous integration is encountering issues as the ci job gets killed because of OutOfMemoryError
This may originates from models requiring migration (Wrong Model Detected)

**Comment by lfasani** [comment]
Problème détecté:
{code}
java.lang.LinkageError: loader constraint violation for class org.eclipse.elk.graph.text.ui.ElkGraphExecutableExtensionFactory: when selecting overriding method 'com.google.inject.Injector org.eclipse.elk.graph.text.ui.ElkGraphExecutableExtensionFactory.getInjector()' the class loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5d6ffae0 of the selected method's type org.eclipse.elk.graph.text.ui.ElkGraphExecutableExtensionFactory, and the class loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6106e3e for its super type org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory have different Class objects for the type com.google.inject.Injector used in the signature (org.eclipse.elk.graph.text.ui.ElkGraphExecutableExtensionFactory is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @5d6ffae0, parent loader 'platform'; org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6106e3e, parent loader 'platform')
{code}

In Capella TP {{com.google.inject}} is found in two versions: {{5.0.1}} and {{3.0.0}}
The issue comes from the fact that there is two versions of this plugin. We are in the case where two dependency plugin paths lead to the usage of two different versions of {{com.google.inject}}(A uses "com.google.inject v1" and B and B uses  "com.google.inject v2")

Among, the features included in the Capella TP, only {{org.eclipse.viatra}} uses the old 3.0.1 version.

Note that viatra is not included in the Capella product. 
* It is is in the Capella TP, so we have the issue in dev environment.
* It is also present in {{org.polarsys.capella.viatra.core.feature}} so we would have the issue as soon as this feature is installed.

Two possible solutions:
* remove Capella viatra feature(which I guess is not acceptable :) ). Nevertheless, I am asking the question: do you intend to keep this feature. What is it used for?
* remove the [dependency to com.google.inject from viatra|https://github.com/viatra/org.eclipse.viatra/blob/d422bcc626a99c4640c0d13931f393ccea0d2326/query/plugins/org.eclipse.viatra.query.patternlanguage.emf.ui/META-INF/MANIFEST.MF#LL26C1-L26C43]

*Solution retenue*
Le feature Capella {{org.polarsys.capella.viatra.core.feature}} utilise dorénavant la feature {{org.eclipse.viatra.query.runtime.feature}} and not {{org.eclipse.viatra.query.sdk.feature}} anymore.
Ci dessous les plugins en moins suite à la résolution de la TP Capella avec les feature {{viatra.runtime}} + {{xtext.xbase.lib}}
{code}
com.google.inject.multibindings.source_3.0.0.v201605172100.jar
com.google.inject.multibindings_3.0.0.v201605172100.jar
com.google.inject.source_3.0.0.v201605172100.jar
com.google.inject.source_5.0.1.v20221112-0806.jar
com.google.inject_3.0.0.v201605172100.jar
com.google.inject_5.0.1.v20221112-0806.jar
io.github.classgraph.source_4.8.149.v20220915-0556.jar
io.github.classgraph_4.8.149.v20220915-0556.jar
org.antlr.runtime.source_3.2.0.v20220404-1927.jar
org.antlr.runtime_3.2.0.v20220404-1927.jar
org.aopalliance.source_1.0.0.v20220404-1927.jar
org.aopalliance_1.0.0.v20220404-1927.jar
org.apache.commons.io.source_2.8.0.v20210415-0900.jar
org.apache.commons.io_2.8.0.v20210415-0900.jar  -> remplacé par org.apache.commons.commons-io_2.11.0.jar
org.eclipse.viatra.addon.databinding.runtime.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.databinding.runtime.validation.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.databinding.runtime.validation_2.7.1.202208301145.jar
org.eclipse.viatra.addon.databinding.runtime_2.7.1.202208301145.jar
org.eclipse.viatra.addon.querybasedfeatures.runtime.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.querybasedfeatures.runtime.validation.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.querybasedfeatures.runtime.validation_2.7.1.202208301145.jar
org.eclipse.viatra.addon.querybasedfeatures.runtime_2.7.1.202208301145.jar
org.eclipse.viatra.addon.querybasedfeatures.tooling.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.querybasedfeatures.tooling_2.7.1.202208301145.jar
org.eclipse.viatra.addon.validation.core.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.validation.core_2.7.1.202208301145.jar
org.eclipse.viatra.addon.validation.runtime.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.validation.runtime.ui.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.validation.runtime.ui_2.7.1.202208301145.jar
org.eclipse.viatra.addon.validation.runtime.validation.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.validation.runtime.validation_2.7.1.202208301145.jar
org.eclipse.viatra.addon.validation.runtime_2.7.1.202208301145.jar
org.eclipse.viatra.addon.validation.tooling.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.validation.tooling_2.7.1.202208301145.jar
org.eclipse.viatra.addon.viewers.runtime.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.viewers.runtime.validation.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.viewers.runtime.validation_2.7.1.202208301145.jar
org.eclipse.viatra.addon.viewers.runtime_2.7.1.202208301145.jar
org.eclipse.viatra.addon.viewers.tooling.ui.source_2.7.1.202208301145.jar
org.eclipse.viatra.addon.viewers.tooling.ui_2.7.1.202208301145.jar
org.eclipse.viatra.documentation.help_2.7.1.202208301145.jar
org.eclipse.viatra.query.patternlanguage.emf.ide.source_2.7.1.202208301145.jar
org.eclipse.viatra.query.patternlanguage.emf.ide_2.7.1.202208301145.jar
org.eclipse.viatra.query.patternlanguage.emf.source_2.7.1.202208301145.jar
org.eclipse.viatra.query.patternlanguage.emf.ui.source_2.7.1.202208301145.jar
org.eclipse.viatra.query.patternlanguage.emf.ui_2.7.1.202208301145.jar
org.eclipse.viatra.query.patternlanguage.emf_2.7.1.202208301145.jar
org.eclipse.viatra.query.runtime.ui.source_2.7.1.202208301145.jar
org.eclipse.viatra.query.runtime.ui_2.7.1.202208301145.jar
org.eclipse.viatra.query.testing.core.source_2.7.1.202208301145.jar
org.eclipse.viatra.query.testing.core_2.7.1.202208301145.jar
org.eclipse.viatra.query.testing.snapshot.source_2.7.1.202208301145.jar
org.eclipse.viatra.query.testing.snapshot_2.7.1.202208301145.jar
org.eclipse.viatra.query.testing.ui.source_2.7.1.202208301145.jar
org.eclipse.viatra.query.testing.ui_2.7.1.202208301145.jar
org.eclipse.viatra.query.tooling.core.source_2.7.1.202208301145.jar
org.eclipse.viatra.query.tooling.core_2.7.1.202208301145.jar
org.eclipse.viatra.query.tooling.generator.model.source_2.7.1.202208301145.jar
org.eclipse.viatra.query.tooling.generator.model.ui.source_2.7.1.202208301145.jar
org.eclipse.viatra.query.tooling.generator.model.ui_2.7.1.202208301145.jar
org.eclipse.viatra.query.tooling.generator.model_2.7.1.202208301145.jar
org.eclipse.viatra.query.tooling.ui.source_2.7.1.202208301145.jar
org.eclipse.viatra.query.tooling.ui_2.7.1.202208301145.jar
org.eclipse.viatra.transformation.evm.source_2.7.1.202208301145.jar
org.eclipse.viatra.transformation.evm.transactions.source_2.7.1.202208301145.jar
org.eclipse.viatra.transformation.evm.transactions_2.7.1.202208301145.jar
org.eclipse.viatra.transformation.evm_2.7.1.202208301145.jar
org.eclipse.viatra.transformation.runtime.emf.source_2.7.1.202208301145.jar
org.eclipse.viatra.transformation.runtime.emf_2.7.1.202208301145.jar
org.eclipse.viatra.transformation.ui.source_2.7.1.202208301145.jar
org.eclipse.viatra.transformation.ui_2.7.1.202208301145.jar
org.eclipse.viatra.transformation.views.source_2.7.1.202208301145.jar
org.eclipse.viatra.transformation.views_2.7.1.202208301145.jar
org.eclipse.xtend.core.source_2.30.0.v20230227-1300.jar
org.eclipse.xtend.core_2.30.0.v20230227-1300.jar
org.eclipse.xtend.ide.common.source_2.30.0.v20230227-1300.jar
org.eclipse.xtend.ide.common_2.30.0.v20230227-1300.jar
org.eclipse.xtend.ide.source_2.30.0.v20230227-1300.jar
org.eclipse.xtend.ide_2.30.0.v20230227-1300.jar
org.eclipse.xtend.lib.macro.source_2.30.0.v20230227-1111.jar
org.eclipse.xtend.lib.macro_2.30.0.v20230227-1111.jar
org.eclipse.xtend.lib.source_2.30.0.v20230227-1111.jar
org.eclipse.xtend.lib_2.30.0.v20230227-1111.jar
org.eclipse.xtext.builder.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.builder.standalone.source_2.30.0.v20230227-1128.jar
org.eclipse.xtext.builder.standalone_2.30.0.v20230227-1128.jar
org.eclipse.xtext.builder_2.30.0.v20230227-1159.jar
org.eclipse.xtext.buildship.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.buildship_2.30.0.v20230227-1159.jar
org.eclipse.xtext.common.types.edit.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.common.types.edit_2.30.0.v20230227-1159.jar
org.eclipse.xtext.common.types.shared.jdt38.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.common.types.shared.jdt38_2.30.0.v20230227-1159.jar
org.eclipse.xtext.common.types.shared.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.common.types.shared_2.30.0.v20230227-1159.jar
org.eclipse.xtext.common.types.source_2.30.0.v20230227-1128.jar
org.eclipse.xtext.common.types.ui.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.common.types.ui_2.30.0.v20230227-1159.jar
org.eclipse.xtext.common.types_2.30.0.v20230227-1128.jar
org.eclipse.xtext.ecore.source_2.30.0.v20230227-1128.jar
org.eclipse.xtext.ecore_2.30.0.v20230227-1128.jar
org.eclipse.xtext.ide.source_2.30.0.v20230227-1116.jar
org.eclipse.xtext.ide_2.30.0.v20230227-1116.jar
org.eclipse.xtext.java.source_2.30.0.v20230227-1128.jar
org.eclipse.xtext.java_2.30.0.v20230227-1128.jar
org.eclipse.xtext.junit4.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.junit4_2.30.0.v20230227-1159.jar
org.eclipse.xtext.logging.source_1.2.24.v20230227-1159.jar
org.eclipse.xtext.logging_1.2.24.v20230227-1159.jar
org.eclipse.xtext.m2e.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.m2e_2.30.0.v20230227-1159.jar
org.eclipse.xtext.smap.source_2.30.0.v20230227-1128.jar
org.eclipse.xtext.smap_2.30.0.v20230227-1128.jar
org.eclipse.xtext.source_2.30.0.v20230227-1116.jar
org.eclipse.xtext.ui.codemining.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.ui.codemining_2.30.0.v20230227-1159.jar
org.eclipse.xtext.ui.codetemplates.ide.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.ui.codetemplates.ide_2.30.0.v20230227-1159.jar
org.eclipse.xtext.ui.codetemplates.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.ui.codetemplates.ui.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.ui.codetemplates.ui_2.30.0.v20230227-1159.jar
org.eclipse.xtext.ui.codetemplates_2.30.0.v20230227-1159.jar
org.eclipse.xtext.ui.shared.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.ui.shared_2.30.0.v20230227-1159.jar
org.eclipse.xtext.ui.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.ui_2.30.0.v20230227-1159.jar
org.eclipse.xtext.util.source_2.30.0.v20230227-1116.jar
org.eclipse.xtext.util_2.30.0.v20230227-1116.jar
org.eclipse.xtext.xbase.ide.source_2.30.0.v20230227-1128.jar
org.eclipse.xtext.xbase.ide_2.30.0.v20230227-1128.jar
org.eclipse.xtext.xbase.source_2.30.0.v20230227-1128.jar
org.eclipse.xtext.xbase.ui.source_2.30.0.v20230227-1159.jar
org.eclipse.xtext.xbase.ui_2.30.0.v20230227-1159.jar
org.eclipse.xtext.xbase_2.30.0.v20230227-1128.jar
org.eclipse.xtext.xtext.ide.source_2.30.0.v20230227-1116.jar
org.eclipse.xtext.xtext.ide_2.30.0.v20230227-1116.jar
org.eclipse.xtext_2.30.0.v20230227-1116.jar
{code}
